<?php
/**
 * PutVideoGeyserApi
 * PHP version 5
 *
 * @category Class
 * @package  Everlesson
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace Everlesson\Api;

use \Everlesson\Configuration;
use \Everlesson\ApiClient;
use \Everlesson\ApiException;
use \Everlesson\ObjectSerializer;

/**
 * PutVideoGeyserApi Class Doc Comment
 *
 * @category Class
 * @package  Everlesson
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PutVideoGeyserApi
{

    /**
     * API Client
     * @var \Everlesson\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \Everlesson\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('http://api.memberportal.io/v0');
        }
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
     * @return \Everlesson\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
  
    /**
     * Set the API client
     * @param \Everlesson\ApiClient $apiClient set the API client
     * @return PutVideoGeyserApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
  
    
    /**
     * putVideoGeyser
     *
     * 
     *
     * @param string $token token (required)
     * @param int $product_id product id or category id (required)
     * @param int $membership_id membership id (required)
     * @param string $category_name category name (required)
     * @param int $category_id category id (required)
     * @param string $video_url video url (required)
     * @param string $video_keywords video keywords (optional)
     * @param string $video_title video title (optional)
     * @param int $video_id video id for updating same video (optional)
     * @param string $video_description video description (optional)
     * @param string $video_cta video CTA (optional)
     * @return \Everlesson\Model\VideoPageGeyser
     * @throws \Everlesson\ApiException on non-2xx response
     */
    public function putVideoGeyser($token, $product_id, $membership_id, $category_name, $category_id, $video_url, $video_keywords = null, $video_title = null, $video_id = null, $video_description = null, $video_cta = null)
    {
        list($response, $statusCode, $httpHeader) = $this->putVideoGeyserWithHttpInfo ($token, $product_id, $membership_id, $category_name, $category_id, $video_url, $video_keywords, $video_title, $video_id, $video_description, $video_cta);
        return $response; 
    }


    /**
     * putVideoGeyserWithHttpInfo
     *
     * 
     *
     * @param string $token token (required)
     * @param int $product_id product id or category id (required)
     * @param int $membership_id membership id (required)
     * @param string $category_name category name (required)
     * @param int $category_id category id (required)
     * @param string $video_url video url (required)
     * @param string $video_keywords video keywords (optional)
     * @param string $video_title video title (optional)
     * @param int $video_id video id for updating same video (optional)
     * @param string $video_description video description (optional)
     * @param string $video_cta video CTA (optional)
     * @return Array of \Everlesson\Model\VideoPageGeyser, HTTP status code, HTTP response headers (array of strings)
     * @throws \Everlesson\ApiException on non-2xx response
     */
    public function putVideoGeyserWithHttpInfo($token, $product_id, $membership_id, $category_name, $category_id, $video_url, $video_keywords = null, $video_title = null, $video_id = null, $video_description = null, $video_cta = null)
    {
        
        // verify the required parameter 'token' is set
        if ($token === null) {
            throw new \InvalidArgumentException('Missing the required parameter $token when calling putVideoGeyser');
        }
        // verify the required parameter 'product_id' is set
        if ($product_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $product_id when calling putVideoGeyser');
        }
        // verify the required parameter 'membership_id' is set
        if ($membership_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $membership_id when calling putVideoGeyser');
        }
        // verify the required parameter 'category_name' is set
        if ($category_name === null) {
            throw new \InvalidArgumentException('Missing the required parameter $category_name when calling putVideoGeyser');
        }
        // verify the required parameter 'category_id' is set
        if ($category_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $category_id when calling putVideoGeyser');
        }
        // verify the required parameter 'video_url' is set
        if ($video_url === null) {
            throw new \InvalidArgumentException('Missing the required parameter $video_url when calling putVideoGeyser');
        }
  
        // parse inputs
        $resourcePath = "/putVideoGeyser";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/x-www-form-urlencoded'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // form params
        if ($token !== null) {
            
            
            $formParams['token'] = $this->apiClient->getSerializer()->toFormValue($token);
            
        }// form params
        if ($product_id !== null) {
            
            
            $formParams['product_id'] = $this->apiClient->getSerializer()->toFormValue($product_id);
            
        }// form params
        if ($membership_id !== null) {
            
            
            $formParams['membership_id'] = $this->apiClient->getSerializer()->toFormValue($membership_id);
            
        }// form params
        if ($category_name !== null) {
            
            
            $formParams['category_name'] = $this->apiClient->getSerializer()->toFormValue($category_name);
            
        }// form params
        if ($category_id !== null) {
            
            
            $formParams['category_id'] = $this->apiClient->getSerializer()->toFormValue($category_id);
            
        }// form params
        if ($video_url !== null) {
            
            
            $formParams['video_url'] = $this->apiClient->getSerializer()->toFormValue($video_url);
            
        }// form params
        if ($video_keywords !== null) {
            
            
            $formParams['video_keywords'] = $this->apiClient->getSerializer()->toFormValue($video_keywords);
            
        }// form params
        if ($video_title !== null) {
            
            
            $formParams['video_title'] = $this->apiClient->getSerializer()->toFormValue($video_title);
            
        }// form params
        if ($video_id !== null) {
            
            
            $formParams['video_id'] = $this->apiClient->getSerializer()->toFormValue($video_id);
            
        }// form params
        if ($video_description !== null) {
            
            
            $formParams['video_description'] = $this->apiClient->getSerializer()->toFormValue($video_description);
            
        }// form params
        if ($video_cta !== null) {
            
            
            $formParams['video_cta'] = $this->apiClient->getSerializer()->toFormValue($video_cta);
            
        }
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, '\Everlesson\Model\VideoPageGeyser'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Everlesson\ObjectSerializer::deserialize($response, '\Everlesson\Model\VideoPageGeyser', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Everlesson\ObjectSerializer::deserialize($e->getResponseBody(), '\Everlesson\Model\VideoPageGeyser', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
}
