<?php
/**
 * PutVideopageApi
 * PHP version 5
 *
 * @category Class
 * @package  Everlesson
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace Everlesson\Api;

use \Everlesson\Configuration;
use \Everlesson\ApiClient;
use \Everlesson\ApiException;
use \Everlesson\ObjectSerializer;

/**
 * PutVideopageApi Class Doc Comment
 *
 * @category Class
 * @package  Everlesson
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PutVideopageApi
{

    /**
     * API Client
     * @var \Everlesson\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \Everlesson\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('http://api.memberportal.io/v0');
        }
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
     * @return \Everlesson\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
  
    /**
     * Set the API client
     * @param \Everlesson\ApiClient $apiClient set the API client
     * @return PutVideopageApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
  
    
    /**
     * putVideopage
     *
     * 
     *
     * @param string $token token (required)
     * @param string $product_id product id or category id (required)
     * @param string $membership_id membership id (required)
     * @param string $page_title module page title (required)
     * @param string $page_description module page description (required)
     * @param string $video_title video title (required)
     * @param string $video_code video embed code (required)
     * @param string $video_thumbnail video thumbnail image (required)
     * @param string $packages packages list (separated by comma) (optional)
     * @return \Everlesson\Model\Videopage[]
     * @throws \Everlesson\ApiException on non-2xx response
     */
    public function putVideopage($token, $product_id, $membership_id, $page_title, $page_description, $video_title, $video_code, $video_thumbnail, $packages = null)
    {
        list($response, $statusCode, $httpHeader) = $this->putVideopageWithHttpInfo ($token, $product_id, $membership_id, $page_title, $page_description, $video_title, $video_code, $video_thumbnail, $packages);
        return $response; 
    }


    /**
     * putVideopageWithHttpInfo
     *
     * 
     *
     * @param string $token token (required)
     * @param string $product_id product id or category id (required)
     * @param string $membership_id membership id (required)
     * @param string $page_title module page title (required)
     * @param string $page_description module page description (required)
     * @param string $video_title video title (required)
     * @param string $video_code video embed code (required)
     * @param string $video_thumbnail video thumbnail image (required)
     * @param string $packages packages list (separated by comma) (optional)
     * @return Array of \Everlesson\Model\Videopage[], HTTP status code, HTTP response headers (array of strings)
     * @throws \Everlesson\ApiException on non-2xx response
     */
    public function putVideopageWithHttpInfo($token, $product_id, $membership_id, $page_title, $page_description, $video_title, $video_code, $video_thumbnail, $packages = null)
    {
        
        // verify the required parameter 'token' is set
        if ($token === null) {
            throw new \InvalidArgumentException('Missing the required parameter $token when calling putVideopage');
        }
        // verify the required parameter 'product_id' is set
        if ($product_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $product_id when calling putVideopage');
        }
        // verify the required parameter 'membership_id' is set
        if ($membership_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $membership_id when calling putVideopage');
        }
        // verify the required parameter 'page_title' is set
        if ($page_title === null) {
            throw new \InvalidArgumentException('Missing the required parameter $page_title when calling putVideopage');
        }
        // verify the required parameter 'page_description' is set
        if ($page_description === null) {
            throw new \InvalidArgumentException('Missing the required parameter $page_description when calling putVideopage');
        }
        // verify the required parameter 'video_title' is set
        if ($video_title === null) {
            throw new \InvalidArgumentException('Missing the required parameter $video_title when calling putVideopage');
        }
        // verify the required parameter 'video_code' is set
        if ($video_code === null) {
            throw new \InvalidArgumentException('Missing the required parameter $video_code when calling putVideopage');
        }
        // verify the required parameter 'video_thumbnail' is set
        if ($video_thumbnail === null) {
            throw new \InvalidArgumentException('Missing the required parameter $video_thumbnail when calling putVideopage');
        }
  
        // parse inputs
        $resourcePath = "/putVideopage";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/x-www-form-urlencoded'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // form params
        if ($token !== null) {
            
            
            $formParams['token'] = $this->apiClient->getSerializer()->toFormValue($token);
            
        }// form params
        if ($product_id !== null) {
            
            
            $formParams['product_id'] = $this->apiClient->getSerializer()->toFormValue($product_id);
            
        }// form params
        if ($membership_id !== null) {
            
            
            $formParams['membership_id'] = $this->apiClient->getSerializer()->toFormValue($membership_id);
            
        }// form params
        if ($page_title !== null) {
            
            
            $formParams['page_title'] = $this->apiClient->getSerializer()->toFormValue($page_title);
            
        }// form params
        if ($page_description !== null) {
            
            
            $formParams['page_description'] = $this->apiClient->getSerializer()->toFormValue($page_description);
            
        }// form params
        if ($video_title !== null) {
            
            
            $formParams['video_title'] = $this->apiClient->getSerializer()->toFormValue($video_title);
            
        }// form params
        if ($video_code !== null) {
            
            
            $formParams['video_code'] = $this->apiClient->getSerializer()->toFormValue($video_code);
            
        }// form params
        if ($video_thumbnail !== null) {
            
            
            $formParams['video_thumbnail'] = $this->apiClient->getSerializer()->toFormValue($video_thumbnail);
            
        }// form params
        if ($packages !== null) {
            
            
            $formParams['packages'] = $this->apiClient->getSerializer()->toFormValue($packages);
            
        }
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, '\Everlesson\Model\Videopage[]'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Everlesson\ObjectSerializer::deserialize($response, '\Everlesson\Model\Videopage[]', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Everlesson\ObjectSerializer::deserialize($e->getResponseBody(), '\Everlesson\Model\Videopage[]', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
}
