<?php
/**
 * RemovePackageApi
 * PHP version 5
 *
 * @category Class
 * @package  Everlesson
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace Everlesson\Api;

use \Everlesson\Configuration;
use \Everlesson\ApiClient;
use \Everlesson\ApiException;
use \Everlesson\ObjectSerializer;

/**
 * RemovePackageApi Class Doc Comment
 *
 * @category Class
 * @package  Everlesson
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RemovePackageApi
{

    /**
     * API Client
     * @var \Everlesson\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \Everlesson\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('http://api.memberportal.io/v0');
        }
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
     * @return \Everlesson\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
  
    /**
     * Set the API client
     * @param \Everlesson\ApiClient $apiClient set the API client
     * @return RemovePackageApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
  
    
    /**
     * removingpackage
     *
     * 
     *
     * @param string $token token (required)
     * @param int $package_id package_id (required)
     * @param int $member_id member_id (required)
     * @return \Everlesson\Model\Removingpackage
     * @throws \Everlesson\ApiException on non-2xx response
     */
    public function removingpackage($token, $package_id, $member_id)
    {
        list($response, $statusCode, $httpHeader) = $this->removingpackageWithHttpInfo ($token, $package_id, $member_id);
        return $response; 
    }


    /**
     * removingpackageWithHttpInfo
     *
     * 
     *
     * @param string $token token (required)
     * @param int $package_id package_id (required)
     * @param int $member_id member_id (required)
     * @return Array of \Everlesson\Model\Removingpackage, HTTP status code, HTTP response headers (array of strings)
     * @throws \Everlesson\ApiException on non-2xx response
     */
    public function removingpackageWithHttpInfo($token, $package_id, $member_id)
    {
        
        // verify the required parameter 'token' is set
        if ($token === null) {
            throw new \InvalidArgumentException('Missing the required parameter $token when calling removingpackage');
        }
        // verify the required parameter 'package_id' is set
        if ($package_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $package_id when calling removingpackage');
        }
        // verify the required parameter 'member_id' is set
        if ($member_id === null) {
            throw new \InvalidArgumentException('Missing the required parameter $member_id when calling removingpackage');
        }
  
        // parse inputs
        $resourcePath = "/removePackage";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/x-www-form-urlencoded'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // form params
        if ($token !== null) {
            
            
            $formParams['token'] = $this->apiClient->getSerializer()->toFormValue($token);
            
        }// form params
        if ($package_id !== null) {
            
            
            $formParams['package_id'] = $this->apiClient->getSerializer()->toFormValue($package_id);
            
        }// form params
        if ($member_id !== null) {
            
            
            $formParams['member_id'] = $this->apiClient->getSerializer()->toFormValue($member_id);
            
        }
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, '\Everlesson\Model\Removingpackage'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Everlesson\ObjectSerializer::deserialize($response, '\Everlesson\Model\Removingpackage', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Everlesson\ObjectSerializer::deserialize($e->getResponseBody(), '\Everlesson\Model\Removingpackage', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
}
