<?php
/**
 * TokenApi
 * PHP version 5
 *
 * @category Class
 * @package  Everlesson
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace Everlesson\Api;

use \Everlesson\Configuration;
use \Everlesson\ApiClient;
use \Everlesson\ApiException;
use \Everlesson\ObjectSerializer;

/**
 * TokenApi Class Doc Comment
 *
 * @category Class
 * @package  Everlesson
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TokenApi
{

    /**
     * API Client
     * @var \Everlesson\ApiClient instance of the ApiClient
     */
    protected $apiClient;
  
    /**
     * Constructor
     * @param \Everlesson\ApiClient|null $apiClient The api client to use
     */
    function __construct($apiClient = null)
    {
        if ($apiClient == null) {
            $apiClient = new ApiClient();
            $apiClient->getConfig()->setHost('http://api.memberportal.io/v0');
        }
  
        $this->apiClient = $apiClient;
    }
  
    /**
     * Get API client
     * @return \Everlesson\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
  
    /**
     * Set the API client
     * @param \Everlesson\ApiClient $apiClient set the API client
     * @return TokenApi
     */
    public function setApiClient(ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
  
    
    /**
     * generateToken
     *
     * 
     *
     * @param string $api_key api key (required)
     * @param string $secret_key secret key (required)
     * @param string $referer_url referer url (required)
     * @param string $referer_ip referer ip (required)
     * @return \Everlesson\Model\Token
     * @throws \Everlesson\ApiException on non-2xx response
     */
    public function generateToken($api_key, $secret_key, $referer_url, $referer_ip)
    {
        list($response, $statusCode, $httpHeader) = $this->generateTokenWithHttpInfo ($api_key, $secret_key, $referer_url, $referer_ip);
        return $response; 
    }


    /**
     * generateTokenWithHttpInfo
     *
     * 
     *
     * @param string $api_key api key (required)
     * @param string $secret_key secret key (required)
     * @param string $referer_url referer url (required)
     * @param string $referer_ip referer ip (required)
     * @return Array of \Everlesson\Model\Token, HTTP status code, HTTP response headers (array of strings)
     * @throws \Everlesson\ApiException on non-2xx response
     */
    public function generateTokenWithHttpInfo($api_key, $secret_key, $referer_url, $referer_ip)
    {
        
        // verify the required parameter 'api_key' is set
        if ($api_key === null) {
            throw new \InvalidArgumentException('Missing the required parameter $api_key when calling generateToken');
        }
        // verify the required parameter 'secret_key' is set
        if ($secret_key === null) {
            throw new \InvalidArgumentException('Missing the required parameter $secret_key when calling generateToken');
        }
        // verify the required parameter 'referer_url' is set
        if ($referer_url === null) {
            throw new \InvalidArgumentException('Missing the required parameter $referer_url when calling generateToken');
        }
        // verify the required parameter 'referer_ip' is set
        if ($referer_ip === null) {
            throw new \InvalidArgumentException('Missing the required parameter $referer_ip when calling generateToken');
        }
  
        // parse inputs
        $resourcePath = "/token";
        $httpBody = '';
        $queryParams = array();
        $headerParams = array();
        $formParams = array();
        $_header_accept = ApiClient::selectHeaderAccept(array('application/json'));
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = ApiClient::selectHeaderContentType(array('application/x-www-form-urlencoded'));
  
        
        
        
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // form params
        if ($api_key !== null) {
            
            
            $formParams['api_key'] = $this->apiClient->getSerializer()->toFormValue($api_key);
            
        }// form params
        if ($secret_key !== null) {
            
            
            $formParams['secret_key'] = $this->apiClient->getSerializer()->toFormValue($secret_key);
            
        }// form params
        if ($referer_url !== null) {
            
            
            $formParams['referer_url'] = $this->apiClient->getSerializer()->toFormValue($referer_url);
            
        }// form params
        if ($referer_ip !== null) {
            
            
            $formParams['referer_ip'] = $this->apiClient->getSerializer()->toFormValue($referer_ip);
            
        }
        
  
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath, 'POST',
                $queryParams, $httpBody,
                $headerParams, '\Everlesson\Model\Token'
            );
            
            if (!$response) {
                return array(null, $statusCode, $httpHeader);
            }

            return array(\Everlesson\ObjectSerializer::deserialize($response, '\Everlesson\Model\Token', $httpHeader), $statusCode, $httpHeader);
            
        } catch (ApiException $e) {
            switch ($e->getCode()) { 
            case 200:
                $data = \Everlesson\ObjectSerializer::deserialize($e->getResponseBody(), '\Everlesson\Model\Token', $e->getResponseHeaders());
                $e->setResponseObject($data);
                break;
            }
  
            throw $e;
        }
    }
    
}
